sample: "tmp"
R1: "testdata/data/1_depth10000_spike0.00010_R1.fastq.gz"
R2: "testdata/data/1_depth10000_spike0.00010_R2.fastq.gz"
bindir: ""
assembly: ""
docker_coverm: "docker://ghcr.io/vdblab/coverm:0.6.1"