# containers:
docker_abricate: "docker://staphb/abricate:1.0.0"
docker_amrfinder: "docker://nickp60/amrfinder:3.10.24"
docker_antismash: "docker://antismash/standalone:6.1.1"
docker_bbtools: "docker://staphb/bbtools:38.97"
docker_biobakery: "docker://ghcr.io/vdblab/biobakery-profiler:20230418a"
docker_biopython: "docker://nanozoo/biopython:1.74--b03961c"
docker_bowtie2: "docker://ghcr.io/vdblab/bowtie2:2.5.0"
docker_bmtagger: "docker://ghcr.io/vdblab/kneaddata-bmtagger:0.6.1"
docker_coverm: "docker://ghcr.io/vdblab/coverm:0.6.1"
docker_cutadapt: "docker://ghcr.io/vdblab/cutadapt:3.7"
docker_dbcan: "docker://haidyi/run_dbcan:3.0.1"
docker_fastqc: "docker://staphb/fastqc:0.11.9"
docker_gtdbtk: "docker://ecogenomic/gtdbtk:2.3.2"
docker_hla: "docker://humanlongevity/hla:0.0.0"
docker_kneaddata: "docker://nickp60/kneaddata-bmtagger:0.1.0"
docker_kraken: "docker://lgallagh/kraken2:2.1.2"
docker_krona: "docker://nanozoo/krona:2.7.1--e7615f7"
docker_megahit: "docker://ghcr.io/vdblab/megahit:5f329c6d24a1480b75145a4c14567a25453b95bf"
docker_metaerg: "docker://ghcr.io/vdblab/metaerg:1.2.3d"
docker_metawrap: "docker://ghcr.io/vdblab/metawrap:1.3"
docker_optitype: "docker://fred2/optitype"
docker_phanta: "docker://ghcr.io/vdblab/phanta:1.1.0-dev"
docker_rgi: "docker://ghcr.io/vdblab/rgi:6.0.0"
docker_seqkit: "docker://ghcr.io/vdblab/seqkit:2.3.1"
docker_snap: "docker://ghcr.io/vdblab/snap-aligner:2.0.1"
docker_sortmerna: "docker://ghcr.io/vdblab/sortmerna:4.3.6"
docker_spades: "docker://staphb/spades:3.15.4"
docker_quast: "docker://staphb/quast:5.0.2"
