sample: "tmp"
R1:"$PWD/testdata/data/1_depth10000_spike0.00010_R1.fastq.gz"
R2:"$PWD/testdata/data/1_depth10000_spike0.00010_R1.fastq.gz"


# containers:
docker_coverm: "docker://ghcr.io/vdblab/coverm:0.6.1"
