R1: ["../testdata/data/1_depth100000_spike0.10000_R1.fastq.gz"]
R2: ["../testdata/data/1_depth100000_spike0.10000_R2.fastq.gz"]
offtarget: "../testdata/data/metawrap/rawbinning_1_depth100000_spike0.10000/concoct/concoct_bins/"
#assembly: "../testdata/data/spades_1_depth100000_spike0.10000.assembly.fasta"
mapper: minimap2-sr
offtarget: None
sample: "testsample"
pctid_threshold: 0.97
length_threshold: 0.97

# references
checkm_db: "/data/brinkvd/resources/dbs/checkm/2015_01_16/"
docker_coverm: "docker://ghcr.io/vdblab/coverm:0.6.1"
